/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.forms;

import utils.Validations;

/**
 *
 * @author Cassandra
 */
public class VtnDepartamento extends javax.swing.JFrame
{

    /**
     * Creates new form VtnDepartamento
     */
    public VtnDepartamento()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        numTelefono = new javax.swing.JTextField();
        departamento = new javax.swing.JTextField();
        jefeDepto = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numTelefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                numTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                numTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(numTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 440, 30));

        departamento.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                departamentoKeyPressed(evt);
            }
        });
        jPanel1.add(departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 440, 30));

        jefeDepto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jefeDeptoActionPerformed(evt);
            }
        });
        jefeDepto.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jefeDeptoKeyPressed(evt);
            }
        });
        jPanel1.add(jefeDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 440, 30));

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 110, 30));

        btnRegistrar.setBackground(new java.awt.Color(102, 255, 102));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/NuevoDepto.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jefeDeptoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jefeDeptoActionPerformed
    {//GEN-HEADEREND:event_jefeDeptoActionPerformed
        
    }//GEN-LAST:event_jefeDeptoActionPerformed

    private void jefeDeptoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jefeDeptoKeyPressed
    {//GEN-HEADEREND:event_jefeDeptoKeyPressed
        Validations.enterEntero(this, evt, jefeDepto, departamento);
    }//GEN-LAST:event_jefeDeptoKeyPressed

    private void departamentoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_departamentoKeyPressed
    {//GEN-HEADEREND:event_departamentoKeyPressed
        Validations.enterCadenaNoVacia(this, evt, departamento, numTelefono);
    }//GEN-LAST:event_departamentoKeyPressed

    private void numTelefonoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numTelefonoKeyPressed
    {//GEN-HEADEREND:event_numTelefonoKeyPressed
        
        
    }//GEN-LAST:event_numTelefonoKeyPressed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void numTelefonoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numTelefonoKeyTyped
    {//GEN-HEADEREND:event_numTelefonoKeyTyped
        Validations.enterCadenaNumTelefono(this, evt, numTelefono, btnRegistrar);
    }//GEN-LAST:event_numTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField departamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jefeDepto;
    private javax.swing.JTextField numTelefono;
    // End of variables declaration//GEN-END:variables
}
